### ISSUE TITLE
Split up EnvoyControlTestConfiguration.kt

### ISSUE THREAD

**Issue by slonka** [allegro/envoy-control#113]
This class contains setup, http clients, stub applications interactions, SUT factories, SUT interactions, some assertions, and cleanup. I think we should consider splitting it :)

_Originally posted by @pzmi in https://github.com/allegro/envoy-control/pull/112_

**Comment by pzmi** [comment]
I thought about a couple things:
- http client as a separate class
- extension methods to separate class(es)
- extract containers as [JUnit5 programmatic extensions](https://junit.org/junit5/docs/current/user-guide/#extensions-registration-programmatic) and group them with their interactions as methods
- use them as needed in a composable way instead of relying on a base class
    - in the beginning, it can still be used in a base class and decide later to split more

All this can be done in small steps, separately :)

**Comment by chemicL** [comment]
Closing as @pbetkier already introduced new ways of setting up tests.
